<a href="https://colab.research.google.com/github/siddhipawar645/Extra_Dataset/blob/main/Extra_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
uploaded=files.upload()
for fn in uploaded.keys():
  print(fn)

Saving Fifa_World_Cup.csv to Fifa_World_Cup.csv
Fifa_World_Cup.csv

In [ ]:
filepath='/content/Fifa_World_Cup.csv'
df=pd.read_csv(filepath)
print(df)

      player_id       player_name  age nationality   team  jersey_number  \
0        P00055        Rodri Fati   26     Spanish  Spain              3
1        P00070   Ansu Le Normand   19     Spanish  Spain             18
2        P00066        Gavi Ramos   18     Spanish  Spain             14
3        P00073     Pedro Cubarsi   20     Spanish  Spain             21
4        P00059  Alvaro Oyarzabal   23     Spanish  Spain              7
...         ...               ...  ...         ...    ...            ...
54595    P00996       Amir Younis   28       Iraqi   Iraq              8
54596    P01006  Safaa Al-Khafaji   20       Iraqi   Iraq             18
54597    P01008     Ahmed Hussein   26       Iraqi   Iraq             20
54598    P00991     Ibrahim Mhawi   30       Iraqi   Iraq              3
54599    P00989  Mohannad Hussein   27       Iraqi   Iraq              1

         position  height_cm  weight_kg preferred_foot  ... feature_16  \
0      Goalkeeper        195         75           Left  ...        416
1      Midfielder        178         75          Right  ...        304
2      Midfielder        177         72           Left  ...        288
3         Forward        182         74          Right  ...        320
4        Defender        191         81           Left  ...        368
...           ...        ...        ...            ...  ...        ...
54595    Defender        177         73          Right  ...        448
54596  Midfielder        176         72          Right  ...        320
54597  Midfielder        173         77           Left  ...        416
54598  Goalkeeper        190         81          Right  ...        480
54599  Goalkeeper        187         73          Right  ...        432

       feature_17 feature_18 feature_19 feature_20 feature_21 feature_22  \
0             442        468        494        520        546        572
1             323        342        361        380        399        418
2             306        324        342        360        378        396
3             340        360        380        400        420        440
4             391        414        437        460        483        506
...           ...        ...        ...        ...        ...        ...
54595         476        504        532        560        588        616
54596         340        360        380        400        420        440
54597         442        468        494        520        546        572
54598         510        540        570        600        630        660
54599         459        486        513        540        567        594

      feature_23 feature_24  feature_25
0            598        624         650
1            437        456         475
2            414        432         450
3            460        480         500
4            529        552         575
...          ...        ...         ...
54595        644        672         700
54596        460        480         500
54597        598        624         650
54598        690        720         750
54599        621        648         675

[54600 rows x 100 columns]

In [ ]:
df.head()

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,416,442,468,494,520,546,572,598,624,650
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,304,323,342,361,380,399,418,437,456,475
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,288,306,324,342,360,378,396,414,432,450
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,320,340,360,380,400,420,440,460,480,500
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,368,391,414,437,460,483,506,529,552,575

In [ ]:
df.tail()

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25
54595,P00996,Amir Younis,28,Iraqi,Iraq,8,Defender,177,73,Right,...,448,476,504,532,560,588,616,644,672,700
54596,P01006,Safaa Al-Khafaji,20,Iraqi,Iraq,18,Midfielder,176,72,Right,...,320,340,360,380,400,420,440,460,480,500
54597,P01008,Ahmed Hussein,26,Iraqi,Iraq,20,Midfielder,173,77,Left,...,416,442,468,494,520,546,572,598,624,650
54598,P00991,Ibrahim Mhawi,30,Iraqi,Iraq,3,Goalkeeper,190,81,Right,...,480,510,540,570,600,630,660,690,720,750
54599,P00989,Mohannad Hussein,27,Iraqi,Iraq,1,Goalkeeper,187,73,Right,...,432,459,486,513,540,567,594,621,648,675

In [ ]:
df.shape

(54600, 100)

In [ ]:
df.columns

Index(['player_id', 'player_name', 'age', 'nationality', 'team',
       'jersey_number', 'position', 'height_cm', 'weight_kg', 'preferred_foot',
       'club_name', 'market_value_eur', 'match_id', 'match_date', 'stadium',
       'city', 'opponent_team', 'tournament_stage', 'match_result',
       'goals_team', 'goals_opponent', 'minutes_played', 'goals', 'assists',
       'shots', 'shots_on_target', 'expected_goals_xg', 'expected_assists_xa',
       'key_passes', 'successful_passes', 'total_passes', 'pass_accuracy',
       'dribbles_attempted', 'successful_dribbles', 'crosses',
       'successful_crosses', 'tackles', 'interceptions', 'clearances',
       'blocks', 'aerial_duels_won', 'aerial_duels_lost', 'recoveries',
       'defensive_actions', 'fouls_committed', 'fouls_suffered',
       'yellow_cards', 'red_cards', 'offsides', 'saves', 'save_percentage',
       'punches', 'clean_sheet', 'goals_conceded', 'penalty_saves',
       'distance_covered_km', 'sprint_distance_km', 'top_speed_kmh',
       'accelerations', 'decelerations', 'stamina_score', 'player_rating',
       'performance_score', 'offensive_contribution', 'defensive_contribution',
       'possession_impact', 'pressure_resistance', 'creativity_score',
       'consistency_score', 'clutch_performance_score',
       'total_goals_tournament', 'total_assists_tournament',
       'total_minutes_tournament', 'player_of_match_awards',
       'tournament_rating', 'feature_1', 'feature_2', 'feature_3', 'feature_4',
       'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9',
       'feature_10', 'feature_11', 'feature_12', 'feature_13', 'feature_14',
       'feature_15', 'feature_16', 'feature_17', 'feature_18', 'feature_19',
       'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24',
       'feature_25'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 100 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 54600 non-null  object
 1   player_name               54600 non-null  object
 2   age                       54600 non-null  int64
 3   nationality               54600 non-null  object
 4   team                      54600 non-null  object
 5   jersey_number             54600 non-null  int64
 6   position                  54600 non-null  object
 7   height_cm                 54600 non-null  int64
 8   weight_kg                 54600 non-null  int64
 9   preferred_foot            54600 non-null  object
 10  club_name                 54600 non-null  object
 11  market_value_eur          54600 non-null  int64
 12  match_id                  54600 non-null  object
 13  match_date                54600 non-null  object
 14  stadium                   54600 non-null  object
 15  city                      54600 non-null  object
 16  opponent_team             54600 non-null  object
 17  tournament_stage          54600 non-null  object
 18  match_result              54600 non-null  object
 19  goals_team                54600 non-null  int64
 20  goals_opponent            54600 non-null  int64
 21  minutes_played            54600 non-null  int64
 22  goals                     54600 non-null  int64
 23  assists                   54600 non-null  int64
 24  shots                     54600 non-null  int64
 25  shots_on_target           54600 non-null  int64
 26  expected_goals_xg         54600 non-null  float64
 27  expected_assists_xa       54600 non-null  float64
 28  key_passes                54600 non-null  int64
 29  successful_passes         54600 non-null  int64
 30  total_passes              54600 non-null  int64
 31  pass_accuracy             54600 non-null  float64
 32  dribbles_attempted        54600 non-null  int64
 33  successful_dribbles       54600 non-null  int64
 34  crosses                   54600 non-null  int64
 35  successful_crosses        54600 non-null  int64
 36  tackles                   54600 non-null  int64
 37  interceptions             54600 non-null  int64
 38  clearances                54600 non-null  int64
 39  blocks                    54600 non-null  int64
 40  aerial_duels_won          54600 non-null  int64
 41  aerial_duels_lost         54600 non-null  int64
 42  recoveries                54600 non-null  int64
 43  defensive_actions         54600 non-null  int64
 44  fouls_committed           54600 non-null  int64
 45  fouls_suffered            54600 non-null  int64
 46  yellow_cards              54600 non-null  int64
 47  red_cards                 54600 non-null  int64
 48  offsides                  54600 non-null  int64
 49  saves                     54600 non-null  int64
 50  save_percentage           54600 non-null  float64
 51  punches                   54600 non-null  int64
 52  clean_sheet               54600 non-null  int64
 53  goals_conceded            54600 non-null  int64
 54  penalty_saves             54600 non-null  int64
 55  distance_covered_km       54600 non-null  float64
 56  sprint_distance_km        54600 non-null  float64
 57  top_speed_kmh             54600 non-null  float64
 58  accelerations             54600 non-null  int64
 59  decelerations             54600 non-null  int64
 60  stamina_score             54600 non-null  float64
 61  player_rating             54600 non-null  float64
 62  performance_score         54600 non-null  float64
 63  offensive_contribution    54600 non-null  float64
 64  defensive_contribution    54600 non-null  float64
 65  possession_impact         54600 non-null  float64
 66  pressure_resistance       54600 non-null  float64
 67  creativity_score          54600 non-null  float64
 68  consistency_score         54600 non-null  float64
 69  clutch_performance_score  54600 non-null  float64
 70  total_goals_tournament    54600 non-null  int64
 71  total_assists_tournament  54600 non-null  int64
 72  total_minutes_tournament  54600 non-null  int64
 73  player_of_match_awards    54600 non-null  int64
 74  tournament_rating         54600 non-null  float64
 75  feature_1                 54600 non-null  int64
 76  feature_2                 54600 non-null  int64
 77  feature_3                 54600 non-null  int64
 78  feature_4                 54600 non-null  int64
 79  feature_5                 54600 non-null  int64
 80  feature_6                 54600 non-null  int64
 81  feature_7                 54600 non-null  int64
 82  feature_8                 54600 non-null  int64
 83  feature_9                 54600 non-null  int64
 84  feature_10                54600 non-null  int64
 85  feature_11                54600 non-null  int64
 86  feature_12                54600 non-null  int64
 87  feature_13                54600 non-null  int64
 88  feature_14                54600 non-null  int64
 89  feature_15                54600 non-null  int64
 90  feature_16                54600 non-null  int64
 91  feature_17                54600 non-null  int64
 92  feature_18                54600 non-null  int64
 93  feature_19                54600 non-null  int64
 94  feature_20                54600 non-null  int64
 95  feature_21                54600 non-null  int64
 96  feature_22                54600 non-null  int64
 97  feature_23                54600 non-null  int64
 98  feature_24                54600 non-null  int64
 99  feature_25                54600 non-null  int64
dtypes: float64(18), int64(68), object(14)
memory usage: 41.7+ MB

In [ ]:
df.describe()

,age,jersey_number,height_cm,weight_kg,market_value_eur,goals_team,goals_opponent,minutes_played,goals,assists,...,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25
count,54600.000000,54600.000000,54600.000000,54600.000000,5.460000e+04,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,...,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000
mean,26.296484,13.500000,181.654341,75.754853,2.008445e+07,1.330476,1.330476,36.199817,0.055385,0.052363,...,420.743736,447.040220,473.336703,499.633187,525.929670,552.226154,578.522637,604.819121,631.115604,657.412088
std,4.067519,7.500069,6.277792,3.951481,2.718866e+07,1.147814,1.147814,36.419755,0.251900,0.239021,...,65.080299,69.147818,73.215336,77.282855,81.350374,85.417892,89.485411,93.552930,97.620448,101.687967
min,17.000000,1.000000,163.000000,65.000000,5.288220e+05,0.000000,0.000000,0.000000,0.000000,0.000000,...,272.000000,289.000000,306.000000,323.000000,340.000000,357.000000,374.000000,391.000000,408.000000,425.000000
25%,23.000000,7.000000,177.000000,73.000000,4.444778e+06,0.000000,0.000000,0.000000,0.000000,0.000000,...,368.000000,391.000000,414.000000,437.000000,460.000000,483.000000,506.000000,529.000000,552.000000,575.000000
50%,26.000000,13.500000,182.000000,76.000000,1.027111e+07,1.000000,1.000000,24.000000,0.000000,0.000000,...,416.000000,442.000000,468.000000,494.000000,520.000000,546.000000,572.000000,598.000000,624.000000,650.000000
75%,29.000000,20.000000,186.000000,78.000000,2.342013e+07,2.000000,2.000000,75.000000,0.000000,0.000000,...,464.000000,493.000000,522.000000,551.000000,580.000000,609.000000,638.000000,667.000000,696.000000,725.000000
max,39.000000,26.000000,200.000000,87.000000,2.000000e+08,7.000000,7.000000,90.000000,4.000000,3.000000,...,624.000000,663.000000,702.000000,741.000000,780.000000,819.000000,858.000000,897.000000,936.000000,975.000000

In [ ]:
df.dtypes

player_id      object
player_name    object
age             int64
nationality    object
team           object
                ...
feature_21      int64
feature_22      int64
feature_23      int64
feature_24      int64
feature_25      int64
Length: 100, dtype: object

In [ ]:
df.isnull().sum()

player_id      0
player_name    0
age            0
nationality    0
team           0
              ..
feature_21     0
feature_22     0
feature_23     0
feature_24     0
feature_25     0
Length: 100, dtype: int64

In [ ]:
df.nunique()

player_id      1248
player_name    1245
age              23
nationality      48
team             48
               ...
feature_21       23
feature_22       23
feature_23       23
feature_24       23
feature_25       23
Length: 100, dtype: int64

In [ ]:
df.sample(7)

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,feature_16,feature_17,feature_18,feature_19,feature_20,feature_21,feature_22,feature_23,feature_24,feature_25
7330,P00392,Cengiz Soyuncu,24,Turkish,Turkey,2,Goalkeeper,183,74,Right,...,384,408,432,456,480,504,528,552,576,600
47620,P00122,Ciro Colpani,26,Italian,Italy,18,Midfielder,177,76,Right,...,416,442,468,494,520,546,572,598,624,650
11675,P01167,Ali Dhaou,18,Tunisian,Tunisia,23,Forward,168,75,Right,...,288,306,324,342,360,378,396,414,432,450
2827,P00894,Hassan Al-Zahrani,30,Saudi,Saudi Arabia,10,Defender,183,73,Right,...,480,510,540,570,600,630,660,690,720,750
3214,P00431,Mykhailo Besedin,21,Ukrainian,Ukraine,15,Midfielder,180,70,Left,...,336,357,378,399,420,441,462,483,504,525
4874,P00223,Ivan Erlic,20,Croatian,Croatia,15,Midfielder,177,70,Left,...,320,340,360,380,400,420,440,460,480,500
34742,P01046,Nayef Boufal,28,Moroccan,Morocco,6,Defender,183,76,Right,...,448,476,504,532,560,588,616,644,672,700

In [ ]:
df.value_counts()

player_id  player_name       age  nationality    team          jersey_number  position    height_cm  weight_kg  preferred_foot  club_name      market_value_eur  match_id  match_date  stadium                  city          opponent_team  tournament_stage  match_result  goals_team  goals_opponent  minutes_played  goals  assists  shots  shots_on_target  expected_goals_xg  expected_assists_xa  key_passes  successful_passes  total_passes  pass_accuracy  dribbles_attempted  successful_dribbles  crosses  successful_crosses  tackles  interceptions  clearances  blocks  aerial_duels_won  aerial_duels_lost  recoveries  defensive_actions  fouls_committed  fouls_suffered  yellow_cards  red_cards  offsides  saves  save_percentage  punches  clean_sheet  goals_conceded  penalty_saves  distance_covered_km  sprint_distance_km  top_speed_kmh  accelerations  decelerations  stamina_score  player_rating  performance_score  offensive_contribution  defensive_contribution  possession_impact  pressure_resistance  creativity_score  consistency_score  clutch_performance_score  total_goals_tournament  total_assists_tournament  total_minutes_tournament  player_of_match_awards  tournament_rating  feature_1  feature_2  feature_3  feature_4  feature_5  feature_6  feature_7  feature_8  feature_9  feature_10  feature_11  feature_12  feature_13  feature_14  feature_15  feature_16  feature_17  feature_18  feature_19  feature_20  feature_21  feature_22  feature_23  feature_24  feature_25
P01248     Mothobi Mvala     29   South African  South Africa  26             Forward     183        82         Right           Club Africain  4868899           M01039    15-06-2026  AT&T Stadium             Dallas        Colombia       Final             L             0           3               66              0      0        1      0                0.03               0.0                  0           14                 17            0.86           1                   0                    0        0                   0        1              0           0       0                 1                  1           1                  1                1               0             0          1         0      0.00             0        0            0               0              7.5                  0.9                 27.0           21             13             90.1           6.1            67.5               57.9                    38.0                    1.2                31.3                 36.6              44.9               21.2                      0                       0                         254                       0                       6.7                29         58         87         116        145        174        203        232        261        290         319         348         377         406         435         464         493         522         551         580         609         638         667         696         725           1
P00001     Kylian Griezmann  24   French         France        1              Goalkeeper  191        81         Right           PSV Eindhoven  16574124          M00024    24-07-2026  Hard Rock Stadium        Miami         Australia      Group Stage       D             1           1               0               0      0        0      0                0.00               0.0                  0           0                  0             0.72           0                   0                    0        0                   0        0              0           0       0                 0                  0           0                  0                0               0             0          0         0      0.00             0        0            0               0              0.0                  0.0                 0.0            0              0              67.8           0.0            2.7                10.6                    90.3                    0.0                71.8                 10.8              66.2               60.2                      0                       0                         348                       0                       0.0                24         48         72         96         120        144        168        192        216        240         264         288         312         336         360         384         408         432         456         480         504         528         552         576         600           1
                                                                                                                                                                 M00089    02-07-2026  Mercedes-Benz Stadium    Atlanta       Spain          Group Stage       W             2           1               0               0      0        0      0                0.00               0.0                  0           0                  0             0.70           0                   0                    0        0                   0        0              0           0       0                 0                  0           0                  0                0               0             0          0         0      0.00             0        0            0               0              0.0                  0.0                 0.0            0              0              54.5           0.0            4.7                6.5                     78.0                    0.0                67.0                 18.0              68.7               67.2                      0                       0                         78                        0                       0.0                24         48         72         96         120        144        168        192        216        240         264         288         312         336         360         384         408         432         456         480         504         528         552         576         600           1
                                                                                                                                                                 M00177    12-07-2026  Hard Rock Stadium        Miami         Canada         Group Stage       W             3           0               0               0      0        0      0                0.00               0.0                  0           0                  0             0.70           0                   0                    0        0                   0        0              0           0       0                 0                  0           0                  0                0               0             0          0         0      0.00             0        0            0               0              0.0                  0.0                 0.0            0              0              80.6           0.0            4.1                1.5                     65.7                    0.0                52.0                 28.0              83.6               50.3                      0                       0                         405                       0                       0.0                24         48         72         96         120        144        168        192        216        240         264         288         312         336         360         384         408         432         456         480         504         528         552         576         600           1
                                                                                                                                                                 M00189    14-07-2026  Gillette Stadium         Boston        Australia      Group Stage       D             0           0               0               0      0        0      0                0.00               0.0                  0           0                  0             0.67           0                   0                    0        0                   0        0              0           0       0                 0                  0           0                  0                0               0             0          0         0      0.00             0        0            0               0              0.0                  0.0                 0.0            0              0              98.5           0.0            0.0                15.5                    89.0                    0.0                71.5                 37.5              68.7               40.2                      0                       0                         426                       0                       0.0                24         48         72         96         120        144        168        192        216        240         264         288         312         336         360         384         408         432         456         480         504         528         552         576         600           1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ..
                                                                                                                                                                 M00385    30-06-2026  Gillette Stadium         Boston        Sweden         Group Stage       L             1           2               75              0      0        0      0                0.00               0.0                  1           8                  13            0.69           1                   0                    1        0                   0        0              3           0       1                 0                  2           3                  1                0               0             0          0         2      0.83             0        0            2               0              6.8                  0.7                 28.5           17             19             91.0           6.1            61.1               4.9                     70.1                    2.2                38.9                 36.0              59.6               48.1                      0                       0                         245                       0                       5.8                24         48         72         96         120        144        168        192        216        240         264         288         312         336         360         384         408         432         456         480         504         528         552         576         600           1
                                                                                                                                                                 M00336    03-07-2026  Lincoln Financial Field  Philadelphia  Croatia        Group Stage       W             2           1               80              0      0        0      0                0.00               0.0                  0           12                 17            0.75           0                   0                    0        0                   0        0              1           0       1                 0                  2           1                  1                0               0             0          0         0      0.00             0        0            1               0              6.9                  0.7                 30.3           16             12             84.9           5.8            55.4               8.8                     74.1                    1.9                44.8                 34.6              60.1               33.2                      0                       0                         166                       0                       5.4                24         48         72         96         120        144        168        192        216        240         264         288         312         336         360         384         408         432         456         480         504         528         552         576         600           1
                                                                                                                                                                 M00310    15-07-2026  Hard Rock Stadium        Miami         Scotland       Group Stage       L             0           4               0               0      0        0      0                0.00               0.0                  0           0                  0             0.95           0                   0                    0        0                   0        0              0           0       0                 0                  0           0                  0                0               0             0          0         0      0.00             0        0            0               0              0.0                  0.0                 0.0            0              0              89.6           0.0            0.0                10.2                    74.9                    0.0                60.0                 43.1              65.8               57.2                      0                       0                         236                       0                       0.0                24         48         72         96         120        144        168        192        216        240         264         288         312         336         360         384         408         432         456         480         504         528         552         576         600           1
                                                                                                                                                                 M00296    17-07-2026  SoFi Stadium             Los Angeles   Scotland       Group Stage       D             1           1               50              0      0        0      0                0.00               0.0                  0           7                  11            0.72           0                   0                    0        0                   0        0              1           0       1                 0                  0           1                  1                0               0             0          0         2      0.91             2        0            0               0              4.4                  0.4                 26.0           15             13             85.3           6.5            61.1               1.0                     91.0                    0.7                61.8                 30.0              71.5               64.4                      0                       0                         283                       0                       6.3                24         48         72         96         120        144        168        192        216        240         264         288         312         336         360         384         408         432         456         480         504         528         552         576         600           1
                                                                                                                                                                 M00288    10-07-2026  Arrowhead Stadium        Kansas City   Ghana          Group Stage       D             1           1               0               0      0        0      0                0.00               0.0                  0           0                  0             0.71           0                   0                    0        0                   0        0              0           0       0                 0                  0           0                  0                0               0             0          0         0      0.00             0        0            0               0              0.0                  0.0                 0.0            0              0              57.7           0.0            0.0                3.2                     86.5                    0.0                69.8                 35.5              62.3               61.5                      0                       0                         401                       0                       0.0                24         48         72         96         120        144        168        192        216        240         264         288         312         336         360         384         408         432         456         480         504         528         552         576         600           1
Name: count, Length: 54600, dtype: int64